[package]
name = "raylib"
version = "3.7.0"
authors = ["DeltaPHC <phclem@protonmail.com>"]
license = "Zlib"
readme = "../README.md"
description = "Safe Rust bindings for Raylib."
documentation = "https://docs.rs/raylib"
repository = "https://github.com/deltaphc/raylib-rs"
keywords = ["bindings", "raylib", "gamedev"]
categories = ["api-bindings", "game-engines", "graphics"]
edition = "2018"

[dependencies]
schemars = "0.8.11"
raylib-sys = { version = "= 3.7.0", path = "../raylib-sys" }
libc = "0.2.45"
lazy_static = "1.2.0"
cfg-if = "1.0.0"
serde = { version = "1.0.125", features = ["derive"], optional = true }
serde_json = { version = "1.0.64", optional = true }
nalgebra = { version = "0.26", optional = true }

[features]
nightly = []
nobuild = ["raylib-sys/nobuild"]
with_serde = ["serde", "serde_json"]
nalgebra_interop = ["nalgebra"]
wayland = ["raylib-sys/wayland"]

[package.metadata.docs.rs]
features = ["nobuild"]
